# Generated by Django 2.2.9 on 2021-08-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210822_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='address',
            new_name='slug',
        ),
    ]
